export const FALLBACK_ZONES = [
  { id: 'z1', name: 'Jakarta Selatan', colorCode: '#0d9488', keywords: ['jaksel', 'jakarta selatan', 'kebayoran', 'cilandak', 'pasar minggu', 'pancoran', 'tebet', 'mampang'] },
  { id: 'z2', name: 'Jakarta Barat', colorCode: '#3b82f6', keywords: ['jakbar', 'jakarta barat', 'grogol', 'kebon jeruk', 'cengkareng', 'kalideres', 'taman sari'] },
  { id: 'z3', name: 'Jakarta Timur', colorCode: '#f59e0b', keywords: ['jaktim', 'jakarta timur', 'cakung', 'duren sawit', 'pulogadung', 'kramat jati', 'jatinegara'] },
  { id: 'z4', name: 'Jakarta Utara', colorCode: '#8b5cf6', keywords: ['jakut', 'jakarta utara', 'kelapa gading', 'tanjung priok', 'penjaringan', 'koja', 'pademangan'] },
  { id: 'z5', name: 'Jakarta Pusat', colorCode: '#ec4899', keywords: ['jakpus', 'jakarta pusat', 'sudirman', 'menteng', 'gambir', 'senen', 'tanah abang'] },
  { id: 'z6', name: 'Bekasi', colorCode: '#ef4444', keywords: ['bekasi', 'jatiasih', 'jatisampurna', 'pondok gede', 'tambun'] },
  { id: 'z7', name: 'Tangerang Selatan', colorCode: '#10b981', keywords: ['tangsel', 'tangerang selatan', 'bsd', 'bintaro', 'serpong', 'ciputat', 'pamulang'] },
  { id: 'z8', name: 'Tangerang Kota', colorCode: '#f97316', keywords: ['tangerang', 'karawaci', 'cipondoh', 'pinang', 'alam sutera'] },
]

export const FALLBACK_PROGRAMS = [
  {
    id: 'p1',
    name: 'Healthy Life Program',
    category: 'healthy_life',
    description: 'Menu sehat seimbang untuk gaya hidup harian.',
    mealTypes: ['lunch_only', 'lunch_dinner'],
    durations: ['weekly_5', 'monthly_20'],
    prices: {
      weekly_5_lunch: 476000,
      weekly_5_lunch_dinner: 791000,
      monthly_20_lunch: 1680000,
      monthly_20_lunch_dinner: 2955000,
    },
  },
  {
    id: 'p2',
    name: 'Busui Premium Program',
    category: 'busui',
    description: 'Menu premium untuk ibu menyusui dengan booster ASI.',
    mealTypes: ['lunch_only', 'lunch_dinner'],
    durations: ['weekly_5', 'monthly_20'],
    prices: {
      weekly_5_lunch: 700000,
      weekly_5_lunch_dinner: 1150000,
      monthly_20_lunch: 2500000,
      monthly_20_lunch_dinner: 4100000,
    },
  },
  {
    id: 'p3',
    name: 'Bumil Program',
    category: 'bumil',
    description: 'Menu khusus ibu hamil, kaya zat besi & folat.',
    mealTypes: ['lunch_only', 'lunch_dinner'],
    durations: ['weekly_5', 'monthly_20'],
    prices: {
      weekly_5_lunch: 600000,
      weekly_5_lunch_dinner: 980000,
      monthly_20_lunch: 2150000,
      monthly_20_lunch_dinner: 3650000,
    },
  },
  {
    id: 'p4',
    name: 'Bulking / Muscle Up Program',
    category: 'bulking',
    description: 'Menu tinggi protein untuk penambahan massa otot.',
    mealTypes: ['lunch_only', 'lunch_dinner'],
    durations: ['weekly_5', 'monthly_20'],
    prices: {
      weekly_5_lunch: 650000,
      weekly_5_lunch_dinner: 1080000,
      monthly_20_lunch: 2300000,
      monthly_20_lunch_dinner: 4000000,
    },
  },
  {
    id: 'p5',
    name: 'IVF Program',
    category: 'ivf',
    description: 'Menu pendukung program bayi tabung.',
    mealTypes: ['lunch_only', 'lunch_dinner'],
    durations: ['weekly_5', 'monthly_20'],
    prices: {
      weekly_5_lunch: 800000,
      weekly_5_lunch_dinner: 1350000,
      monthly_20_lunch: 2900000,
      monthly_20_lunch_dinner: 4900000,
    },
  },
  {
    id: 'p6',
    name: 'Promil - PCOS Program',
    category: 'promil_pcos',
    description: 'Menu program kehamilan untuk penderita PCOS.',
    mealTypes: ['lunch_only', 'lunch_dinner'],
    durations: ['weekly_5', 'monthly_20'],
    prices: {
      weekly_5_lunch: 720000,
      weekly_5_lunch_dinner: 1200000,
      monthly_20_lunch: 2600000,
      monthly_20_lunch_dinner: 4400000,
    },
  },
  {
    id: 'p7',
    name: 'Weight Loss Diet Program',
    category: 'weight_loss',
    description: 'Menu defisit kalori terkontrol untuk penurunan berat badan.',
    mealTypes: ['lunch_only', 'lunch_dinner'],
    durations: ['weekly_5', 'monthly_20'],
    prices: {
      weekly_5_lunch: 550000,
      weekly_5_lunch_dinner: 920000,
      monthly_20_lunch: 1950000,
      monthly_20_lunch_dinner: 3450000,
    },
  },
]
